name: Build and Push Update Automatically

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    
jobs:
  build-win:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: Remove-Item -path .\dist\win-unpacked\ -recurse  # This will make sure that Build Artifact doesn't take a butt load of time to zip up the dist folder I need
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/

  build-mac:

    runs-on: macOS-11

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npm install
    - run: npm run build
    - run: sudo rm -R ./dist/mac/
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/

  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: sudo rm -R ./dist/linux-unpacked/
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/

  release-update:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: sleep 600 # Wait 10 minutes for builds to complete first, then run...
    # Copy new update to the update server
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/* /usr/share/nginx/updates/falix-software/
    
    
    # For FalixNodes Desktop Website
    - run: cd /usr/share/nginx/cdn/falix/desktop/windows/
    - run: sudo rm *
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/* /usr/share/nginx/cdn/falix/desktop/windows/
    - run: sudo mv FalixNodes* falixnodes-desktop-setup.exe
    
    - run: cd /usr/share/nginx/cdn/falix/desktop/mac/
    - run: sudo rm *
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/* /usr/share/nginx/cdn/falix/desktop/mac/
    - run: sudo mv FalixNodes* falixnodes-desktop.dmg

    
    - run: cd /usr/share/nginx/cdn/falix/desktop/linux/
    - run: sudo rm *
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/* /usr/share/nginx/cdn/falix/desktop/linux/
    - run: sudo mv FalixNodes* falixnodes-desktop.AppImage
    
    # Clean Up
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/
    - run: sudo rm *
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/
    - run: sudo rm *
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/
    - run: sudo rm *
    
