name: Release Update

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    
jobs:
  release-update:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    # Copy new update to the update server
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/* /usr/share/nginx/updates/falix-software/
    
    
    # For FalixNodes Desktop Website
    - run: cd /usr/share/nginx/cdn/falix/desktop/
    - run: rmdir windows
    - run: rmdir mac
    - run: rmdir linux
    - run: mkdir windows
    - run: mkdir mac
    - run: mkdir linux
    
    - run: cd windows
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/* /usr/share/nginx/cdn/falix/desktop/windows/
    - run: sudo mv FalixNodes* falixnodes-desktop-setup.exe
    
    - run: cd /usr/share/nginx/cdn/falix/desktop/mac/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/* /usr/share/nginx/cdn/falix/desktop/mac/
    - run: sudo mv FalixNodes* falixnodes-desktop.dmg

    - run: cd /usr/share/nginx/cdn/falix/desktop/linux/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/* /usr/share/nginx/cdn/falix/desktop/linux/
    - run: sudo mv FalixNodes* falixnodes-desktop.AppImage
    
    # Clean Up
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/
    
    
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/
    
    
    - run: cd /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/
    
    
    
